import os
import sys
import re
import json
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="LLM Incident Explanation Middleware")

API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")

# Detect Gemini setup
IS_GEMINI = "googleapis.com" in BASE_URL or API_KEY.startswith("AQ.Ab")
if IS_GEMINI and MODEL == "deepseek-chat":
    MODEL = "gemini-flash-latest"


class IncidentContext(BaseModel):
    decision: str
    reason: str
    src_ip: str
    dst_ip: str
    pattern: str
    ml_score: float
    packets: int
    bytes: int
    ttl: int

def sanitize_string(val):
    # Strip any characters that are not alphanumeric, dots, hyphens, colons, or underscores
    # This prevents prompt injection via attacker-controlled flow strings (like spoofed ports or protocols)
    return re.sub(r"[^a-zA-Z0-9\.\-\_\:]", "", str(val))

def validate_response(data):
    if not isinstance(data, dict):
        return False
    if "summary" not in data or not isinstance(data["summary"], str):
        return False
    if "evidence" not in data or not isinstance(data["evidence"], list):
        return False
    if "confidence_commentary" not in data or not isinstance(data["confidence_commentary"], str):
        return False
    for item in data["evidence"]:
        if not isinstance(item, str):
            return False
    return True

@app.post("/explain")
async def explain_incident(ctx: IncidentContext):
    # 1. Sanitize input parameters to protect against prompt injection
    src_ip = sanitize_string(ctx.src_ip)
    dst_ip = sanitize_string(ctx.dst_ip)
    pattern = sanitize_string(ctx.pattern)
    decision = sanitize_string(ctx.decision)
    reason = re.sub(r"[^a-zA-Z0-9\s\.\,\-\_\(\)\>\:\/]", "", ctx.reason) # Allow spaces and basic punctuation in reason
    
    # 2. Build prompt
    prompt = f"""
You are a senior cybersecurity incident response analyst.
Explain the following policy decision generated by an automated DDoS detection pipeline.

Flow Event Details:
- Source Host: {src_ip}
- Destination Target: {dst_ip}
- Traffic Signature: {pattern}
- Machine Learning Anomaly Score: {ctx.ml_score:.3f}
- Volume: {ctx.packets} packets ({ctx.bytes} bytes)
- Pipeline Policy Decision: {decision.upper()}
- Pipeline Decision Justification: {reason}
- Mitigation Expiry TTL: {ctx.ttl} seconds

Provide a structured incident explanation.
Your response MUST be a valid JSON object matching this schema:
{{
  "summary": "Short explanation of the incident and decision",
  "evidence": ["Point-of-evidence 1", "Point-of-evidence 2"],
  "confidence_commentary": "Analysis of anomaly detection confidence and patterns"
}}

Respond ONLY with the JSON object. Do not include markdown code block syntax (like ```json) or any wrapping text.
"""

    # 3. Call API dynamically (Gemini native vs DeepSeek/OpenAI)
    if IS_GEMINI:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent"
        headers = {
            "Content-Type": "application/json",
            "X-goog-api-key": API_KEY
        }
        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ],
            "systemInstruction": {
                "parts": [
                    {
                        "text": "You are a network security assistant that outputs strictly raw JSON conforming to the requested schema. No code blocks, no chat."
                    }
                ]
            },
            "generationConfig": {
                "responseMimeType": "application/json",
                "temperature": 0.1
            }
        }
        print(f"[*] Calling native Gemini API at {url} (Model: {MODEL}) for incident {src_ip}->{dst_ip}...")
    else:
        url = f"{BASE_URL}/chat/completions"
        headers = {
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": "You are a network security assistant that outputs strictly raw JSON conforming to the requested schema. No code blocks, no chat."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.1
        }
        print(f"[*] Calling OpenAI-compatible API at {url} (Model: {MODEL}) for incident {src_ip}->{dst_ip}...")
    
    try:
        r = requests.post(url, json=payload, headers=headers, timeout=12)
        if r.status_code == 200:
            res_data = r.json()
            if IS_GEMINI:
                content = res_data["candidates"][0]["content"]["parts"][0]["text"].strip()
            else:
                content = res_data["choices"][0]["message"]["content"].strip()
            print(f"[*] Raw LLM response: {content}")
            
            # Clean content if the model accidentally wrapped it in code blocks
            if content.startswith("```"):
                # Strip markdown fence blocks
                content = re.sub(r"^```(?:json)?\n", "", content)
                content = re.sub(r"\n```$", "", content)
                content = content.strip()
                
            parsed_json = json.loads(content)
            
            # 4. Strict Schema Validation
            if validate_response(parsed_json):
                return parsed_json
            else:
                print("[!] LLM response structure validation failed.")
        else:
            print(f"[!] LLM API failed with code {r.status_code}: {r.text}")
    except Exception as e:
        print(f"[!] Exception calling LLM: {e}")
        
    # 5. Schema-Valid Fallback
    print("[*] Returning schema-valid fallback explanation.")
    fallback = {
        "summary": f"Automated system executed {decision} action for source {src_ip} targeting {dst_ip}.",
        "evidence": [
            f"Machine Learning classified traffic pattern as {pattern} with score {ctx.ml_score:.3f}.",
            f"Flow telemetry recorded {ctx.packets} packets and {ctx.bytes} bytes.",
            f"Policy gatekeeper triggered response due to: {reason}."
        ],
        "confidence_commentary": "Calculated deterministically via policy engine hard thresholds and Isolation Forest anomaly score."
    }
    return fallback
